### ISSUE TITLE
Courts returned differ between web and API

### ISSUE THREAD

**Issue by zheileman** [hmcts/courtfinder-search#410]
## Description of the issue

We (https://github.com/ministryofjustice/c100-application) are using the following endpoint to retrieve a list of courts given an AOL and a postcode:

`/search/results.json?aol=Children&postcode=%{postcode}`

It seems like this endpoint is not doing the same filtering and pre-processing of the courts that the web client is doing when returning their results, and in particular, it does not filter by `court__displayed=True`.

This results in a different number of courts (and sometimes different order too) via the API to those returned via web client.

## Impact

We pick the first court returned by the API, as being the closest to the postcode entered by the user. For courts that are no longer in the business, this makes us direct the user to a no longer existing court.

## Example

Take the following postcode: `BN212BH`

1. Get the results via the API:
https://courttribunalfinder.service.gov.uk/search/results.json?aol=Children&postcode=BN212BH

This will return 2 courts.
First one with `"displayed": false` and second one with `"displayed": true`.

If trying to visit this first court slug, an error page is shown:
https://courttribunalfinder.service.gov.uk/courts/eastbourne-county-court-and-family-court

2. Get the results via web client by selecting the option `The Area of Law I am interested in (recommended)` and then `Children`. Enter the above postcode.

This will return only 1 court, the one that in the API JSON representation is marked as `"displayed": true`. It omits the one with `"displayed": false`

However, note the count in the web result is still wrong, as it says `These are the 2 courts or tribunals nearest BN212BH.`

## How to fix it

As a hot-fix, we can filter manually the results on our side, excluding the ones with `"displayed": false` in the JSON.

A better solution and the one we are proposing is, either:

a) The API results are consistent and do the same filtering as the web client, meaning the above API endpoint will return just one court, same as the web client.

b) Expose through the API the ability to filter the results, so that we can pass to the endpoint the flag `displayed` true or false as required.

Any of the above solutions can work for us, although perhaps, and because this problem can happen to others without being aware of, the recommended course of action should be option **(a)** so consumers of the API don't need to change anything on their side and they receive the fix immediately.

If option **(b)** is chosen, we recommend, if flag is not provided, default to only return the courts marked as visible or "displayable", so behaviour is consistent with web client.

## Contact

For any further questions, you can find us in slack channel **#cross_justice_team** or direct message to me. Thank you in advance.

**Comment by kgrecki** [comment]
Closed court shouldn't show up. There was some filtering missing from certain type of searches. It has been fixed now. Thanks.
